development:
  sessions:
    default:
      database: checkin_development
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: checkin_production
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: checkin_test
      hosts:
        - localhost:27017
